### PR TITLE
Fix unlocking error on "Start Mixing"

### LINKED ISSUE #1939: [Qt] Incorrect error message with Start Mixing and Passphrase entry
This is an easy to duplicate issue (on the current develop branch - have not checked other versions) resulting in a misleading error message that could lead someone to think their wallet was locked when it actually is not.

1. Click the `Start Mixing` button while wallet is locked
2. Uncheck the `Only for mixing via PrivateSend` checkbox
unlock - for all
3. Enter correct passphrase and click `OK`
The wallet will report an incorrect error message as shown:
unlock - erroneous error

The wallet is now unlocked (contrary to the error message). Also, mixing is not started.

I think the issue is due to the `requestUnlock` parameter [here](https://github.com/dashpay/dash/blob/develop/src/qt/overviewpage.cpp#L616) being decoupled from the actual state of the checkbox (the `fForMixingOnly` parameter is always true, not based on the checkbox state). This then results in `fMixingUnlockFailed` to be true (if the user supplied the correct password) because the new status of the wallet is `Unlocked`, not `UnlockedForMixingOnly` -
 [reference](https://github.com/dashpay/dash/blob/develop/src/qt/walletmodel.cpp#L597).

### PR DESCRIPTION
**Pull request by UdjinM6**
~Instead warn that wallet is fully unlocked etc.~

Don't even give users an option to unlock their wallets not for mixing when hitting "Start Mixing" button.

Fixes #1939

### CODE REVIEW

File: src/qt/walletmodel.cpp [hunk 1]
```diff
@@ -594,7 +594,7 @@ WalletModel::UnlockContext WalletModel::requestUnlock(bool fForMixingOnly)
     EncryptionStatus encStatusNew = getEncryptionStatus();
 
     // Wallet was locked, user requested to unlock it for mixing and failed to do so
-    bool fMixingUnlockFailed = fForMixingOnly && !(encStatusNew == UnlockedForMixingOnly);
+    bool fMixingUnlockFailed = fForMixingOnly && !(encStatusNew == UnlockedForMixingOnly || encStatusNew == Unlocked);
```
Comment (codablock) [inline src/qt/walletmodel.cpp]: Why not `fForMixingOnly && encStatusNew != UnlockedForMixingOnly && encStatusNew != Unlocked`? Much easier to read IMHO

Comment (UdjinM6) [reply src/qt/walletmodel.cpp]: Hmm... On another thought that's actually equal to `fForMixingOnly && encStatusNew == Locked`.. but there is no reason to check this because `fInvalid` already has `encStatusNew == Locked` as a part of the condition. The whole situation seems a bit illogical now that I think more of it tbh. Should we even allow user to unlock wallet _not_ for mixing this way? Probably not...

**Comment by UdjinM6** [comment]
Pushed an alternative solution, fixed PR description accordingly

**Comment by codablock** [comment]
re-utACK

**Comment by thephez** [comment]
ACK - worked as expected based on the revised description in #1939
