### PR TITLE
Fix exit codes

### LINKED ISSUE #1117: dash-cli --version results in non-zero exit code
When running `dash-cli --version` or `dashd --version` the exit code is 1, as if there was an error. Convention should be a zero exit code for non-errors.

I don't know if this is a bitcoind issue or a dashd issue.

### PR DESCRIPTION
**Pull request by UdjinM6**
- `--help`, `--version` etc should exit with `0` i.e. no error ("not enough args" case should still trigger an error), fixes #1117 
- error reading config file should exit with error
- slightly refactor `AppInitRPC`/`AppInitRawTx` to return standard exit codes (`EXIT_FAILURE`/`EXIT_SUCCESS`) or `CONTINUE_EXECUTION` (-1)
- every `main()`/`exit()` should return/use one of EXIT_ codes instead of magic numbers

### CODE REVIEW

**Comment by crowning-** [comment]
utACK

**Comment by UdjinM6** [comment]
Will probably rework this, closing for now

**Comment by UdjinM6** [comment]
Reworked version: https://github.com/bitcoin/bitcoin/pull/9067 + dash bits (fixing masternode.conf failure and also some code is a bit different in 12.1)

pls re-review :)

File: src/dash-cli.cpp [hunk 1]
```diff
@@ -81,31 +86,35 @@ static bool AppInitRPC(int argc, char* argv[])
...
+        return EXIT_FAILURE;
     }
     if (GetBoolArg("-rpcssl", false))
     {
         fprintf(stderr, "Error: SSL mode for RPC (-rpcssl) is no longer supported.\n");
-        return false;
+        return EXIT_FAILURE;
     }
-    return true;
+    return CONTINUE_EXECUTION;
```
Comment (crowning-) [inline src/dash-cli.cpp]: What's the difference between EXIT_SUCCESS and CONTINUE_EXECUTION?

Comment (UdjinM6) [inline src/dash-cli.cpp]: If function returns `CONTINUE_EXECUTION` then `main()` will continue further, otherwise it will exit with returned code.

**Comment by UdjinM6** [comment]
> There's a lonely return false

Ha! Nicely spotted! 👍  Fixed :)
