### PR TITLE
Serialize the block header in CBlockHeader::GetHash()

### LINKED ISSUE #2520: CBlockHeader::GetHash() must serialize the block header
Disclaimer: This is based on code review only, and not testing. I could be wrong.

Bitcoin:

```c
uint256 CBlockHeader::GetHash() const
{
    return SerializeHash(*this);
}
```

Dash:

```c
uint256 CBlockHeader::GetHash() const
{
    return HashX11(BEGIN(nVersion), END(nNonce));
}
```

This omits serialization. I see no serialization inside `HashX11` either. Some header fields are 32-bit integers in host byte order (the `uint256` ones are host-independent, though). Thus, I expect that Dash core tree as it currently is to malfunction on big-endian systems, and only work right on the currently prevalent little-endian systems.

The fix may be something like this (untested):

```c
uint256 CBlockHeader::GetHash() const
{
    CDataStream ss(SER_NETWORK, PROTOCOL_VERSION);
    ss << *this;
    return HashX11((const char *)&ss[0], (const char *)&ss[0] + ss.size());
}
```

### PR DESCRIPTION
**Pull request by solardiz**
Dash's change of Bitcoin's CBlockHeader::GetHash() to HashX11 omitted the serialization step, which broke portability to big-endian system. Re-add the serialization to restore the portability. Closes #2520.

### CODE REVIEW

**Comment by solardiz** [comment]
That's what I get for submitting untested stuff...

**Comment by solardiz** [comment]
I'm trying to add:

```
  streams.h \
  support/allocators/zeroafterfree.h \
  support/cleanse.cpp \
  support/cleanse.h \
```

to `libdash_consensus_a_SOURCES`. I think adding `support/cleanse.cpp` would be sufficient for builds to succeed, but the convention appears to be to list header dependencies as well, and that's good.

**Comment by solardiz** [comment]
Now Windows builds (I checked the log for one) fail with:

```
support/.libs/libdashconsensus_la-cleanse.o:cleanse.cpp:(.text+0x1e): undefined reference to `OPENSSL_cleanse'
collect2: error: ld returned 1 exit status
Makefile:4224: recipe for target 'libdashconsensus.la' failed
make[2]: *** [libdashconsensus.la] Error 1
```

So I guess we're also not linking against OpenSSL there, and it feels weird to start doing so merely for `OPENSSL_cleanse`. Maybe `memory_cleanse` should be reimplemented such that we don't have this dependency, e.g. by using Colin Percival's `insecure_memzero.[ch]` or reusing (a subset of) the approach(es) from there (function in a separate translation unit; referenced via exported function pointer so the compiler doesn't reliably know the pointer is constant; writes via `volatile char *` pointers).

**Comment by UdjinM6** [comment]
Yeah, I figured it out too... Adjusting `src/Makefile.am` like this https://github.com/UdjinM6/dash/commit/36a21ba9c0ab41accd135987e696c6a5337b0a94#diff-480477e89f9b6ddafb30c4383dcdd705R551 should fix it (https://travis-ci.org/UdjinM6/dash/builds/464113453). But I'm not sure I like the idea of injecting OpenSSL into core consensus stuff (even for such a minor thing). Smth like https://github.com/UdjinM6/dash/commit/f89427f16bfe1e9632548f4d9f9107510433fd65 would be a better solution I think, waiting for Travis (https://travis-ci.org/UdjinM6/dash/builds/464140335) to confirm that I'm not missing smth again 🙈. It seems to have comparable performance too.

**Comment by codablock** [comment]
I would prefer to not add OpenSSL dependencies to anything just because of such a small change.
Alternative solutions:
1. backport https://github.com/bitcoin/bitcoin/pull/11196
2. Use CVectorWriter instead of CDataStream (https://github.com/codablock/dash/commit/389855c0598a86a28a05bbcd1cebffb88f8fd8b8)
This removes the dependency `CDataStream->CSerializeData->zero_after_free_allocator->memory_cleanse`

File: src/primitives/block.cpp [hunk 1]
```diff
@@ -5,14 +5,17 @@
...
+#include "streams.h"
 #include "hash.h"
 #include "tinyformat.h"
 #include "utilstrencodings.h"
 #include "crypto/common.h"
 
 uint256 CBlockHeader::GetHash() const
 {
-    return HashX11(BEGIN(nVersion), END(nNonce));
+    CDataStream ss(SER_NETWORK, PROTOCOL_VERSION);
```
Comment (UdjinM6) [inline src/primitives/block.cpp]: Using CVectorWriter 

```suggestion
    std::vector<unsigned char> vch(80);
    CVectorWriter ss(SER_NETWORK, PROTOCOL_VERSION, vch, 0);
```

File: src/primitives/block.cpp [hunk 2]
```diff
@@ -5,14 +5,17 @@
...
+    ss << *this;
+    return HashX11((const char *)&ss[0], (const char *)&ss[0] + ss.size());
```
Comment (UdjinM6) [inline src/primitives/block.cpp]:
```suggestion
    return HashX11((const char *)vch.data(), (const char *)vch.data() + vch.size());
```

File: src/primitives/block.cpp [hunk 3]
```diff
@@ -5,14 +5,17 @@
 
 #include "primitives/block.h"
 
+#include "streams.h"
 #include "hash.h"
```
Comment (UdjinM6) [inline src/primitives/block.cpp]: Let's sort them alphabetically

```suggestion
#include "hash.h"
#include "streams.h"
```

File: src/primitives/block.cpp [hunk 4]
```diff
@@ -5,14 +5,17 @@
 
 #include "primitives/block.h"
 
+#include "streams.h"
```
Comment (UdjinM6) [inline src/primitives/block.cpp]:
```suggestion
```

File: src/Makefile.am [hunk 5]
```diff
@@ -397,6 +397,10 @@ libdash_consensus_a_SOURCES = \
   script/script_error.cpp \
   script/script_error.h \
   serialize.h \
+  streams.h \
+  support/allocators/zeroafterfree.h \
```
Comment (UdjinM6) [inline src/Makefile.am]: Dropping no longer needed new dependencies

```suggestion
```

File: src/Makefile.am [hunk 6]
```diff
@@ -397,6 +397,10 @@ libdash_consensus_a_SOURCES = \
...
+  support/cleanse.cpp \
```
Comment (UdjinM6) [inline src/Makefile.am]:
```suggestion
```

File: src/Makefile.am [hunk 7]
```diff
@@ -397,6 +397,10 @@ libdash_consensus_a_SOURCES = \
...
+  support/cleanse.h \
```
Comment (UdjinM6) [inline src/Makefile.am]:
```suggestion
```

**Comment by solardiz** [comment]
We're in agreement on not adding a dependency on OpenSSL.

@UdjinM6 Would you like me to accept your many individual "suggestions" using the GitHub UI? That will probably result in many commits, which I guess you intend to squash when merging this PR? Like before, I'd end up relying on your testing, and now this also became mostly your code.

**Comment by codablock** [comment]
@solardiz You can use the "Files changed" view to batch suggestions and then create a single commit from it.

**Comment by solardiz** [comment]
Thanks @codablock. Done.

Here's a concern: we're still including `streams.h`, and IIRC strictly speaking that's enough to bring all of those previously seen dependencies in. We're probably relying on compiler optimization for avoiding those dependencies now. Also, there are probably still dependencies on the extra header file(s) included by `streams.h`, in terms of needing a rebuild of `block.cpp` if those files change - but we only list `streams.h` itself as a dependency now.

**Comment by UdjinM6** [comment]
All green, should be ready to merge. Pls do the final review @codablock @nmarley.

**Comment by solardiz** [comment]
Strictly speaking, maybe we should also `#include "version.h"` for our use of `PROTOCOL_VERSION`.
