### PR TITLE
Fix -liquidityprovider option

### LINKED ISSUE #1815: liquidityprovider broken
This [commit](https://github.com/dashpay/dash/pull/1248/commits/8fcdff25e6a66e55bb463aa1564ceb5f6c477253) broke `-liquidityprovider` feature.
Calling `PrepareDenominate` for each value from `nPrivateSendRounds` to `0` in loop is too heavy (100% cpu load). With `-liquidityprovider` feature (`nPrivateSendRounds` == 99999) we constantly hit timeout.

Log:
```
2017-12-27 07:31:59 CPrivateSendClient::SubmitDenominate -- Running PrivateSend denominate for 99999 rounds, error: Can't select current denominated inputs
...
2017-12-27 07:32:38 CPrivateSendClient::SubmitDenominate -- Running PrivateSend denominate for 82810 rounds, error: Can't select current denominated inputs
2017-12-27 07:32:38 CPrivateSendClient::SubmitDenominate -- Running PrivateSend denominate for 82809 rounds, error: Can't select current denominated inputs
2017-12-27 07:32:38 CPrivateSendClient::CheckTimeout -- Session timed out (30s) -- restting
2017-12-27 07:32:38 CPrivateSendClient::SetState -- nState: 0, nStateNew: 4
2017-12-27 07:32:38 CPrivateSendClient::SubmitDenominate -- Running PrivateSend denominate for 82808 rounds, error: Can't select current denominated inputs
2017-12-27 07:32:38 CPrivateSendClient::SubmitDenominate -- Running PrivateSend denominate for 82807 rounds, error: Incorrect session denom
2017-12-27 07:32:38 CPrivateSendClient::SubmitDenominate -- Running PrivateSend denominate for 82806 rounds, error: Incorrect session denom
...
2017-12-27 07:32:40 CPrivateSendClient::SubmitDenominate -- Running PrivateSend denominate for 2 rounds, error: Incorrect session denom
2017-12-27 07:32:40 CPrivateSendClient::SubmitDenominate -- Running PrivateSend denominate for 1 rounds, error: Incorrect session denom
2017-12-27 07:32:40 CPrivateSendClient::SubmitDenominate -- Running PrivateSend denominate for all rounds, error: Incorrect session denom
```

As a side note: calling `SetNull` before `SetState` cause this strange log outputs like `nState: 0, nStateNew: 4` or `Incorrect session denom`.

### PR DESCRIPTION
**Pull request by UdjinM6**
Reverting the pre-1248 logic for liquidity providers

Fixes #1815

### CODE REVIEW

**Comment by UdjinM6** [comment]
Rebased on develop, will backport into #1828 after merging

File: src/privatesend-client.cpp [hunk 1]
```diff
@@ -1002,13 +1002,24 @@ bool CPrivateSendClient::SubmitDenominate(CConnman& connman)
...
 
     // Submit transaction to the pool if we get here
-    // Try to use only inputs with the same number of rounds starting from the highest number of rounds possible
-    for(int i = nPrivateSendRounds; i > 0; i--) {
-        if(PrepareDenominate(i - 1, i, strError, vecTxDSInRet, vecTxOutRet)) {
-            LogPrintf("CPrivateSendClient::SubmitDenominate -- Running PrivateSend denominate for %d rounds, success\n", i);
-            return SendDenominate(vecTxDSInRet, vecTxOutRet, connman);
+    if (nLiquidityProvider) {
+        // Try to use only inputs with the same number of rounds starting from the lowest number of rounds possible
+        for(int i = 0; i< nPrivateSendRounds; i++) {
```
Comment (willwray) [inline src/privatesend-client.cpp]: Another C vs C++ style nit / chestnut* (chestnit?) - prefer pre inc/dec over post inc/dec.
https://google.github.io/styleguide/cppguide.html#Preincrement_and_Predecrement

Purely style here; i++ is traditional C (especially as a loop index like this) while ++i is idiomatic C++ (which therefore should've been called ++C).

When used in an expression a post-increment has to be read more carefully because it implies state.

* an old chestnut:
a joke or story that has become tedious because of its age and constant repetition.
