### PR TITLE
Fix ProcessNewBlock vs EnforceBestChainLock deadlocks in ActivateBestChain

### LINKED ISSUE #3476: [Bug/Instability] Nodes running on develop keep getting stuck randomly every day or two.
This issue was initially seen by @UdjinM6 on April 10th, 2020. 

When this occurs the node wasn’t receiving blocks and shutdown wasn’t clear

Originally running 26dec64, on ubuntu 16.04

Node was reporting
```
2020-04-10 00:31:17 socket sending timeout: 1201s
...
2020-04-10 00:31:17 socket sending timeout: 1201s
2020-04-10 00:31:22 socket sending timeout: 1201s
```
That node while running 52bf616 had earlier reported 
```
2020-04-07 00:07:30 socket sending timeout: 1201s
2020-04-07 00:07:30 socket sending timeout: 1201s
2020-04-07 00:07:34 socket sending timeout: 1201s
...
2020-04-07 00:07:34 socket sending timeout: 1201s
```

cb33702 was the prior commit that had been being ran since mid January, so the problem(s) was likely introduced between cb33702 and 52bf616

https://github.com/dashpay/dash/pull/3456 which fixes some deadlocks was created with the intent to fix this issue, however, the issue persists

### PR DESCRIPTION
**Pull request by UdjinM6**
It should be ok to skip `SyncWithValidationInterfaceQueue` when called from CL/IS cause it will be triggered whenever `ActivateBestChain` is called by smth else (_e.g. by a block received from p2p_) and we don't expect CL/IS to reorg the chain this much anyway. Not a very elegant solution but should do the job I think.

Note: https://github.com/dashpay/dash/commit/0b3183cc89e8f72ced982c8416a5a6c46676da77?w=1 is just a cleanup to avoid fixing smth that is never really used and 2e136a14e32b4c3898d30de2cb4de915c27d7f34 also unifies the way we handle `ActivateBestChain` failures in IS/CL.

Fixes #3476

### CODE REVIEW

**Comment by UdjinM6** [comment]
Looks like this is not enough unfortunately, see https://github.com/dashpay/dash/issues/3476#issuecomment-630435430. Need some better solution. Closing.

**Comment by PastaPastaPasta** [comment]
can you rebase on develop so travis is happy? https://travis-ci.com/github/PastaPastaPasta/dash/builds/167488704

**Comment by UdjinM6** [comment]
Resurrecting this. The latest commit fixed the second deadlock it seems, my nodes are running fine for 4+ days now.

**Comment by xdustinface** [comment]
Looks also good so far here on my testnet node.. it had it running into the deadlock with the latest `develop` and now it runs on e279acf24db75c49cf17a3780076f3b742907a7e for 2+ days 👍

File: src/validation.cpp [hunk 1]
```diff
@@ -2953,7 +2953,7 @@ bool CChainState::ActivateBestChain(CValidationState &state, const CChainParams&
     do {
         boost::this_thread::interruption_point();
 
-        if (GetMainSignals().CallbacksPending() > 10) {
+        if (fSyncQueue && GetMainSignals().CallbacksPending() > 10) {
```
Comment (xdustinface) [inline src/validation.cpp:2956]: Also codewise it looks overall good to me. Though i wonder if it now even makes any sense to skip the queue sync if `ActivateBestChain` gets called by CL/IS with CL having its own scheduler? Wasn't the issue that CL put `ActivateBestChain` (over edges) in the validation interface scheduler's queue and that basically blocked itself by waiting for the queue it runs from to be done with all tasks? 

@UdjinM6 please correct me if im wrong and explain me your full understanding of the deadlock as i was investigating a lot here how exactly it happens and i just want to fully get it 🙂

**Comment by PastaPastaPasta** [comment]
ran `ubuntu@ubuntu-Ryzen:~/workspace/dash/test/functional$ for n in {1..10}; do python3 test_runner.py -j10 llmq-*; done` 
So running llmq tests 10 times, w/ no test failures, which we had seen in some PRs, I'm gonna try to do this again on travis running tests multiple times.

**Comment by PastaPastaPasta** [comment]
two things:

Use std::bind and std::thread instead of boost::*  https://github.com/PastaPastaPasta/dash/commit/211af7fd3929b202878304e9190c4d64a84bc7a0

(Maybe, CLion suggests this, but I'm not sure if this is something we want / follow)  prefer lambda over std::bind https://github.com/PastaPastaPasta/dash/commit/18915f47f4396737aa09f96aea55a178a880e869

File: src/validation.cpp (hunk 1 above)
Comment (UdjinM6) [reply src/validation.cpp:2956]: Thee are two different cases:
1.
a) CL: LOCK->SyncWithValidationInterfaceQueue
b) PeerLogicValidation: (dead)LOCK

(b) (which is executed as a part of the queue flushing) is waiting for (a) to release the lock which will never happen because (a) is waiting for (b). Even if (a) would be in another scheduler it wouldn't matter, the lock would be held anyway because queue processing is blocked. Skipping SyncWithValidationInterfaceQueue lets (a) to finish and release the lock.

2.
a) PeerLogicValidation: LOCK->SyncWithValidationInterfaceQueue
b) CL: (dead)LOCK

In this case (b) (executed as a regular scheduler job) blocks _the scheduler itself_ not just the queue, it simply can't process anything at this point. Using another scheduler for (b) fixes this because now (b) blocks some another thread and the original scheduler can process all the tasks and release the lock which in its turn lets (b) to continue.

**Comment by UdjinM6** [comment]
@PastaPastaPasta I was just following the surrounding code and usage instructions in https://github.com/dashpay/dash/blob/develop/src/scheduler.h#L23-L34. Scheduler was updated to using `std` over `boost` much later https://github.com/bitcoin/bitcoin/pull/18234

**Comment by PastaPastaPasta** [comment]
Okay, understand

**Comment by PastaPastaPasta** [comment]
Possible problem here? https://travis-ci.com/github/PastaPastaPasta/dash/jobs/339530126

Maybe this is a different problem / ci issue

File: src/validation.cpp (hunk 1 above)
Comment (xdustinface) [reply src/validation.cpp:2956]: Hmm.. soo.. if i look at the two cases you commented in #3476 it looks for me like the queue skipping just fixed one deadlock and introduced a new one. 

Lets assume we have: 

- Thread 1 > `A` > CConnman::ThreadMessageHandler 
- Thread 2 > `B` > Validation Interface Scheduler Thread
- Thread 3 > `C` > New ChainLocks Scheduler Thread
- Thread 4 > `D` > CInstantSendManager::WorkThreadMain
- Thread 5 > `E` > CSigSharesManager::WorkThreadMain
### Case 1 

**1a)** `B` runs `ActivateBestChain` it locks `cs_activateBestChain` and then since there are more than 10 tasks in its queue it adds another one and waits for this other one to finish which can never happen because it waits for itself. 

**1b)** Now `A` gets a new block message, wants to process it and therefor also calls `ActivateBestChain` and waits for `cs_activateBestChain` to release which won’t happen because of the above.. 

### Case 2 / Skipping the sync for CL code

If we skip the sync now Case 1 can’t longer happen because in **1a)** `B` will lock `cs_activateBestChain`, skips the sync (and with this it skips the wait on yourself), runs the rest of `ActivateBestChain` and then it releases `cs_activateBestChain` which means `A` will not wait forever for `cs_activateBestChain`.. This gives us just the new deadlock below:

**2a)** `A` gets a new block, wants to process it and calls `ActivateBestChain`. It locks `cs_activateBestChain` and since there are more than 10 tasks in the queue of `B` it adds another task to the queue of `B` and waits for this other task to finish.

**2b)** `B` which has at this point more than 10 tasks (one of them is `ActivateBestChain` which it got from the CL code with sync skipping) processes its tasks until it comes to the call of `ActivateBestChain` where it then waits for `cs_activateBestChain` to release whihc won't happen because `A` in **2a)** locked it. 

### Fix the deadlock / Adding Thread C

Soo.. the actual reason for the deadlock is IMO only calling `ActivateBestChain` from `B`. Means just adding `C` should be the fix for the initial deadlock and then deadlock 2 will never be introduced. 

And this is a problem now because we have the “Let Thread B” catch up thing here introduced in  #3376 https://github.com/dashpay/dash/blob/0662f170f09f5d1304d80e41754b59c9d56528d8/src/validation.cpp#L2956-L2961 
which leads to `X` waiting for `B` if `X` calls `ActivateBestChain` **and** there are more than 10 queue entries (which is why the deadlock happened randomly and more often on the mainnet it seems) and therefor `B` waiting for itself if `ActivateBestChain` gets called by `B` .  

So i would say having this "skip sync" code included makes no sense anymore because if `ActivateBestChain` gets called from instantsend code its called by `D` or `E` and if its called by CL its called by `C`. So there should be no more deadlock, not?

Does this make sense? Note: I'm tired now so i hope i didn't miss any other crazy magic 🤣

Comment (UdjinM6) [reply src/validation.cpp]: I think I understand now, thanks 👍 Reverted, let's see :)

**Comment by PastaPastaPasta** [comment]
re: llmq-simplepose.py fails about 1 in 100 times for me locally
