### PR TITLE
Fix crash, issue #977

### LINKED ISSUE #977: Masternode crash in CMasternodePayments::CleanPaymentList
My masternode crashes every few weeks with an seg fault. Now i got a core dump. It crashed in masternode-payments.cpp:607
`if(chainActive.Tip()->nHeight` - winner.nBlockHeight > nLimit){
I think it is a race condition because to call chainActive.Tip() there should be cs_main locked, but i am not sure if this is the problem. Btw, I am on the master branch.

### PR DESCRIPTION
**Pull request by UdjinM6**
Try to quickly lock `cs_main` before accessing `chainActive` in masternode payments, should probably fix #977 and some related crashes.

Using `TRY_LOCK` here so it _should not_ result in new potential deadlock. Also failing to lock and stopping function execution should be ok since missing one message or one specific tick for cleaning out old winners is not critical. Failing in `IsScheduled` _should not_ be an issue either imo since for the vast majority of masternodes this should return `false` anyway.

Reviewer wanted :)

EDIT: Testers wanted too :D

### CODE REVIEW

File: src/masternode-payments.cpp [hunk 1]
```diff
@@ -367,17 +367,22 @@ void CMasternodePayments::ProcessMessageMasternodePayments(CNode* pfrom, std::st
 
         if(pfrom->nVersion < MIN_MNW_PEER_PROTO_VERSION) return;
 
-        if(chainActive.Tip() == NULL) return;
+        int nHeight;
+        {
+            TRY_LOCK(cs_main, locked);
```
Comment (tgflynn) [inline src/masternode-payments.cpp]: Careful, I don't think TRY_LOCK necessarily guarantees you won't deadlock, unless any other held locks are also TRY_LOCK'd.

Still given a choice between a rare deadlock and a rare segfault I would probably go for the deadlock, it's probably less likely to be exploitable.  I recommend this be tested for a few days though before it's merged, just too make sure the deadlocks aren't too common.

Comment (UdjinM6) [inline src/masternode-payments.cpp]: I agree, this should be tested. Updated PR description ;)

**Comment by tgflynn** [comment]
I have the patched version running on the test server (on mainnet).

**Comment by tgflynn** [comment]
The test server has had an instance running this patch for the past 5 days so I think it should be fairly safe to merge this.

ACK

**Comment by UdjinM6** [comment]
no crashes for me too, merging
