### PR TITLE
qt: Fix labels in transaction list

### LINKED ISSUE #3992: Labeling on the addresses does not work.
I was testing the MNs on testnet when realized that the rewards which arrive and are seen on the tx history tab are the alfanumeric addresses even though on the moment of requesting the label has been given.
BC018695-79FA-4D42-AB8B-7E0E229F4C95
EFCFD7F7-3EA7-490A-9CEA-28246AAA8B63

### PR DESCRIPTION
**Pull request by UdjinM6**
Fixes #3992

### CODE REVIEW

File: src/qt/transactiontablemodel.cpp [hunk 1]
```diff
@@ -205,6 +204,15 @@ class TransactionTablePriv
             int64_t adjustedTime;
             if (rec->statusUpdateNeeded(numBlocks, parent->getChainLockHeight()) && wallet.tryGetTxStatus(rec->hash, wtx, adjustedTime)) {
                 rec->updateStatus(wtx, numBlocks, adjustedTime, parent->getChainLockHeight());
+                // Update label
+                if (IsValidDestination(rec->txDest)) {
+                    std::string name;
+                    if (wallet.getAddress(rec->txDest, &name)) {
+                        rec->status.label = QString::fromStdString(name);
+                    } else{
```
Comment (xdustinface) [inline src/qt/transactiontablemodel.cpp:212]:
```suggestion
                    } else {
```

**Review by xdustinface — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK
